POST http://localhost:5000/api/genimage
Content-Type: application/json

{
    "id": 9,
    "prompt": "a green slug climbing mount everest. remember the summers of childhood in the style of childrens show",
    "n": 1,
    "size": "512x512"
}